final:
  issue:
    jira:
      server-url: https://iimik.atlassian.net
      project-code: AIO
  api:
    yapi:
      enable: true
      server-url: ${YAPI_SERVER_URL}
      token: ${YAPI_TOKEN}
    markdown:
      enable: true
